/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnviadasIndexRouteImport } from './routes/enviadas/index'
import { Route as EnviadasIdRouteImport } from './routes/enviadas/$id'
import { Route as EnviarIndexRouteImport } from './routes/enviar/index'
import { Route as EnviarSucessoRouteImport } from './routes/enviar/sucesso'
import { Route as EquipeIndexRouteImport } from './routes/equipe/index'
import { Route as InicioIndexRouteImport } from './routes/inicio/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingAguardandoRouteImport } from './routes/onboarding/aguardando'
import { Route as OnboardingNegadoRouteImport } from './routes/onboarding/negado'
import { Route as PainelIndexRouteImport } from './routes/painel/index'
import { Route as PedidosIndexRouteImport } from './routes/pedidos/index'
import { Route as PedidosIdRouteImport } from './routes/pedidos/$id'
import { Route as PedidosNovoRouteImport } from './routes/pedidos/novo'
import { Route as PerfilIndexRouteImport } from './routes/perfil/index'
import { Route as EnviarTipoIndexRouteImport } from './routes/enviar/$tipo/index'
import { Route as EnviarTipoDestinatariosRouteImport } from './routes/enviar/$tipo/destinatarios'
import { Route as EnviarTipoRevisarRouteImport } from './routes/enviar/$tipo/revisar'
import { Route as InicioMsgIdRouteImport } from './routes/inicio/msg/$id'
import { Route as PainelSecretariaIdRouteImport } from './routes/painel/secretaria.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviadasIndexRoute = EnviadasIndexRouteImport.update({
  id: '/enviadas/',
  path: '/enviadas/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviadasIdRoute = EnviadasIdRouteImport.update({
  id: '/enviadas/$id',
  path: '/enviadas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviarIndexRoute = EnviarIndexRouteImport.update({
  id: '/enviar/',
  path: '/enviar/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviarSucessoRoute = EnviarSucessoRouteImport.update({
  id: '/enviar/sucesso',
  path: '/enviar/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeIndexRoute = EquipeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EquipeRoute,
} as any)
const InicioIndexRoute = InicioIndexRouteImport.update({
  id: '/inicio/',
  path: '/inicio/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAguardandoRoute = OnboardingAguardandoRouteImport.update({
  id: '/onboarding/aguardando',
  path: '/onboarding/aguardando',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingNegadoRoute = OnboardingNegadoRouteImport.update({
  id: '/onboarding/negado',
  path: '/onboarding/negado',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIdRoute = PedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosNovoRoute = PedidosNovoRouteImport.update({
  id: '/pedidos/novo',
  path: '/pedidos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviarTipoIndexRoute = EnviarTipoIndexRouteImport.update({
  id: '/enviar/$tipo/',
  path: '/enviar/$tipo/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviarTipoDestinatariosRoute = EnviarTipoDestinatariosRouteImport.update({
  id: '/enviar/$tipo/destinatarios',
  path: '/enviar/$tipo/destinatarios',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviarTipoRevisarRoute = EnviarTipoRevisarRouteImport.update({
  id: '/enviar/$tipo/revisar',
  path: '/enviar/$tipo/revisar',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioMsgIdRoute = InicioMsgIdRouteImport.update({
  id: '/inicio/msg/$id',
  path: '/inicio/msg/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelSecretariaIdRoute = PainelSecretariaIdRouteImport.update({
  id: '/painel/secretaria/$id',
  path: '/painel/secretaria/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipe': typeof EquipeRouteWithChildren
  '/login': typeof LoginRoute
  '/enviadas/$id': typeof EnviadasIdRoute
  '/enviar/sucesso': typeof EnviarSucessoRoute
  '/onboarding/aguardando': typeof OnboardingAguardandoRoute
  '/onboarding/negado': typeof OnboardingNegadoRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/pedidos/novo': typeof PedidosNovoRoute
  '/enviadas/': typeof EnviadasIndexRoute
  '/enviar/': typeof EnviarIndexRoute
  '/equipe/': typeof EquipeIndexRoute
  '/inicio/': typeof InicioIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/enviar/$tipo/destinatarios': typeof EnviarTipoDestinatariosRoute
  '/enviar/$tipo/revisar': typeof EnviarTipoRevisarRoute
  '/inicio/msg/$id': typeof InicioMsgIdRoute
  '/painel/secretaria/$id': typeof PainelSecretariaIdRoute
  '/enviar/$tipo/': typeof EnviarTipoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/enviadas/$id': typeof EnviadasIdRoute
  '/enviar/sucesso': typeof EnviarSucessoRoute
  '/onboarding/aguardando': typeof OnboardingAguardandoRoute
  '/onboarding/negado': typeof OnboardingNegadoRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/pedidos/novo': typeof PedidosNovoRoute
  '/enviadas': typeof EnviadasIndexRoute
  '/enviar': typeof EnviarIndexRoute
  '/equipe': typeof EquipeIndexRoute
  '/inicio': typeof InicioIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/painel': typeof PainelIndexRoute
  '/pedidos': typeof PedidosIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/enviar/$tipo/destinatarios': typeof EnviarTipoDestinatariosRoute
  '/enviar/$tipo/revisar': typeof EnviarTipoRevisarRoute
  '/inicio/msg/$id': typeof InicioMsgIdRoute
  '/painel/secretaria/$id': typeof PainelSecretariaIdRoute
  '/enviar/$tipo': typeof EnviarTipoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipe': typeof EquipeRouteWithChildren
  '/login': typeof LoginRoute
  '/enviadas/$id': typeof EnviadasIdRoute
  '/enviar/sucesso': typeof EnviarSucessoRoute
  '/onboarding/aguardando': typeof OnboardingAguardandoRoute
  '/onboarding/negado': typeof OnboardingNegadoRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/pedidos/novo': typeof PedidosNovoRoute
  '/enviadas/': typeof EnviadasIndexRoute
  '/enviar/': typeof EnviarIndexRoute
  '/equipe/': typeof EquipeIndexRoute
  '/inicio/': typeof InicioIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/enviar/$tipo/destinatarios': typeof EnviarTipoDestinatariosRoute
  '/enviar/$tipo/revisar': typeof EnviarTipoRevisarRoute
  '/inicio/msg/$id': typeof InicioMsgIdRoute
  '/painel/secretaria/$id': typeof PainelSecretariaIdRoute
  '/enviar/$tipo/': typeof EnviarTipoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/equipe'
    | '/login'
    | '/enviadas/$id'
    | '/enviar/sucesso'
    | '/onboarding/aguardando'
    | '/onboarding/negado'
    | '/pedidos/$id'
    | '/pedidos/novo'
    | '/enviadas/'
    | '/enviar/'
    | '/equipe/'
    | '/inicio/'
    | '/onboarding/'
    | '/painel/'
    | '/pedidos/'
    | '/perfil/'
    | '/enviar/$tipo/destinatarios'
    | '/enviar/$tipo/revisar'
    | '/inicio/msg/$id'
    | '/painel/secretaria/$id'
    | '/enviar/$tipo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/enviadas/$id'
    | '/enviar/sucesso'
    | '/onboarding/aguardando'
    | '/onboarding/negado'
    | '/pedidos/$id'
    | '/pedidos/novo'
    | '/enviadas'
    | '/enviar'
    | '/equipe'
    | '/inicio'
    | '/onboarding'
    | '/painel'
    | '/pedidos'
    | '/perfil'
    | '/enviar/$tipo/destinatarios'
    | '/enviar/$tipo/revisar'
    | '/inicio/msg/$id'
    | '/painel/secretaria/$id'
    | '/enviar/$tipo'
  id:
    | '__root__'
    | '/'
    | '/equipe'
    | '/login'
    | '/enviadas/$id'
    | '/enviar/sucesso'
    | '/onboarding/aguardando'
    | '/onboarding/negado'
    | '/pedidos/$id'
    | '/pedidos/novo'
    | '/enviadas/'
    | '/enviar/'
    | '/equipe/'
    | '/inicio/'
    | '/onboarding/'
    | '/painel/'
    | '/pedidos/'
    | '/perfil/'
    | '/enviar/$tipo/destinatarios'
    | '/enviar/$tipo/revisar'
    | '/inicio/msg/$id'
    | '/painel/secretaria/$id'
    | '/enviar/$tipo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipeRoute: typeof EquipeRouteWithChildren
  LoginRoute: typeof LoginRoute
  EnviadasIdRoute: typeof EnviadasIdRoute
  EnviarSucessoRoute: typeof EnviarSucessoRoute
  OnboardingAguardandoRoute: typeof OnboardingAguardandoRoute
  OnboardingNegadoRoute: typeof OnboardingNegadoRoute
  PedidosIdRoute: typeof PedidosIdRoute
  PedidosNovoRoute: typeof PedidosNovoRoute
  EnviadasIndexRoute: typeof EnviadasIndexRoute
  EnviarIndexRoute: typeof EnviarIndexRoute
  InicioIndexRoute: typeof InicioIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  PainelIndexRoute: typeof PainelIndexRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  EnviarTipoDestinatariosRoute: typeof EnviarTipoDestinatariosRoute
  EnviarTipoRevisarRoute: typeof EnviarTipoRevisarRoute
  InicioMsgIdRoute: typeof InicioMsgIdRoute
  PainelSecretariaIdRoute: typeof PainelSecretariaIdRoute
  EnviarTipoIndexRoute: typeof EnviarTipoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enviadas/': {
      id: '/enviadas/'
      path: '/enviadas'
      fullPath: '/enviadas/'
      preLoaderRoute: typeof EnviadasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enviadas/$id': {
      id: '/enviadas/$id'
      path: '/enviadas/$id'
      fullPath: '/enviadas/$id'
      preLoaderRoute: typeof EnviadasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enviar/': {
      id: '/enviar/'
      path: '/enviar'
      fullPath: '/enviar/'
      preLoaderRoute: typeof EnviarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enviar/sucesso': {
      id: '/enviar/sucesso'
      path: '/enviar/sucesso'
      fullPath: '/enviar/sucesso'
      preLoaderRoute: typeof EnviarSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/': {
      id: '/equipe/'
      path: '/'
      fullPath: '/equipe/'
      preLoaderRoute: typeof EquipeIndexRouteImport
      parentRoute: typeof EquipeRoute
    }
    '/inicio/': {
      id: '/inicio/'
      path: '/inicio'
      fullPath: '/inicio/'
      preLoaderRoute: typeof InicioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/aguardando': {
      id: '/onboarding/aguardando'
      path: '/onboarding/aguardando'
      fullPath: '/onboarding/aguardando'
      preLoaderRoute: typeof OnboardingAguardandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/negado': {
      id: '/onboarding/negado'
      path: '/onboarding/negado'
      fullPath: '/onboarding/negado'
      preLoaderRoute: typeof OnboardingNegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$id': {
      id: '/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof PedidosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/novo': {
      id: '/pedidos/novo'
      path: '/pedidos/novo'
      fullPath: '/pedidos/novo'
      preLoaderRoute: typeof PedidosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enviar/$tipo/': {
      id: '/enviar/$tipo/'
      path: '/enviar/$tipo'
      fullPath: '/enviar/$tipo/'
      preLoaderRoute: typeof EnviarTipoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enviar/$tipo/destinatarios': {
      id: '/enviar/$tipo/destinatarios'
      path: '/enviar/$tipo/destinatarios'
      fullPath: '/enviar/$tipo/destinatarios'
      preLoaderRoute: typeof EnviarTipoDestinatariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enviar/$tipo/revisar': {
      id: '/enviar/$tipo/revisar'
      path: '/enviar/$tipo/revisar'
      fullPath: '/enviar/$tipo/revisar'
      preLoaderRoute: typeof EnviarTipoRevisarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio/msg/$id': {
      id: '/inicio/msg/$id'
      path: '/inicio/msg/$id'
      fullPath: '/inicio/msg/$id'
      preLoaderRoute: typeof InicioMsgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/secretaria/$id': {
      id: '/painel/secretaria/$id'
      path: '/painel/secretaria/$id'
      fullPath: '/painel/secretaria/$id'
      preLoaderRoute: typeof PainelSecretariaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EquipeRouteChildren {
  EquipeIndexRoute: typeof EquipeIndexRoute
}

const EquipeRouteChildren: EquipeRouteChildren = {
  EquipeIndexRoute: EquipeIndexRoute,
}

const EquipeRouteWithChildren =
  EquipeRoute._addFileChildren(EquipeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipeRoute: EquipeRouteWithChildren,
  LoginRoute: LoginRoute,
  EnviadasIdRoute: EnviadasIdRoute,
  EnviarSucessoRoute: EnviarSucessoRoute,
  OnboardingAguardandoRoute: OnboardingAguardandoRoute,
  OnboardingNegadoRoute: OnboardingNegadoRoute,
  PedidosIdRoute: PedidosIdRoute,
  PedidosNovoRoute: PedidosNovoRoute,
  EnviadasIndexRoute: EnviadasIndexRoute,
  EnviarIndexRoute: EnviarIndexRoute,
  InicioIndexRoute: InicioIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  PainelIndexRoute: PainelIndexRoute,
  PedidosIndexRoute: PedidosIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  EnviarTipoDestinatariosRoute: EnviarTipoDestinatariosRoute,
  EnviarTipoRevisarRoute: EnviarTipoRevisarRoute,
  InicioMsgIdRoute: InicioMsgIdRoute,
  PainelSecretariaIdRoute: PainelSecretariaIdRoute,
  EnviarTipoIndexRoute: EnviarTipoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
